sudo isn't required when using Homebrew
Homebrew returns an error when using `sudo`:

```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```